name: Deploy to IPFS via Pinata

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: IPFS Pinata deploy GitHub action
        uses: popovoleksandr/ipfs-pinata-deploy-action@v1.6.3
        with:
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET_KEY }}
