name: Deploy to IPFS via Pinata

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: IPFS Pinata deploy GitHub action
        id: deploy
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: 'Decentralized website'
          path: './build'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
          verbose: true
          remove-old: true
      
      - name: Get the output hash
        run: echo "The hash was ${{ steps.deploy.outputs.hash }}"
      
      # - name: Print IPFS URL
      #   run: echo "Server running on: https://ipfs.io/ipfs/${{ steps.deploy.outputs.hash }}"